changeLogFile=changelogs/master.xml
url=jdbc:sqlserver://localhost:1433;databaseName=liquibase_test;encrypt=true;trustServerCertificate=true
username=sa
password=YourStrong!Passw0rd
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
liquibase.hub.mode=OFF
